...

diff --git a/lib/pkg b/lib/pkg
--- a/lib/pkg
+++ b/lib/pkg
@@ -13,11 +13,13 @@ ___x_cmd_dev_pkg_lsmod_getfp(){
 }
 
 ___x_cmd_dev_pkg_lsmod(){
-    local fp
-    fp="$(___x_cmd_dev_pkg_lsmod_getfp)" || {
-        printf "Cannot find file modlist.\n" >&2
-        return
-    }
+    local fp="${MODLIST:-""}"
+    if [ -z "$fp" ]; then
+        fp="$(___x_cmd_dev_pkg_lsmod_getfp)" || {
+            printf "Cannot find file modlist.\n" >&2
+            return
+        }
+    fi
 
     awk -v mode="${1:-all}" '
 ($0!="")&&($0 !~ /[ ]*#/){
