...

diff --git a/lib/release b/lib/release
--- a/lib/release
+++ b/lib/release
@@ -50,6 +50,30 @@ A
 }
 # EndSection
 
+# Section: pub
+___x_cmd_yanfa_release_pub()(
+    param:void
+    # set -o errexit
+    if {
+        x log :yanfa warn "<release-pub> update"
+        ___x_cmd_yanfa_release_update "${CONCURRENCY:-7}"
+    } && {
+        x log :yanfa warn "<release-pub> create tgz"
+        ___x_cmd_yanfa_release_tgz "$@"
+        x log :yanfa warn "<release-pub> create tgz exit: $?"
+    } && {
+        x log :yanfa warn "<release-pub> Add && Commit && Push"
+        git add . && git commit -m ... && ___x_cmd_yanfa_ws_push
+        x log :yanfa warn "<release-pub> Add && Commit && Push exit: $?"
+    }; then
+        x log :yanfa warn "<release-pub> OK"
+    else
+        x log :yanfa warn "<release-pub> Fail"
+        return 1
+    fi
+)
+# EndSection
+
 # Section: module add pull update
 ___x_cmd_yanfa_release_gitx(){
     if [ -z "$___X_CMD_IN_CHINA_NET" ]; then
@@ -172,27 +196,6 @@ ___x_cmd_yanfa_release_wc(){
 
 # EndSection
 
-___x_cmd_yanfa_release_pub()(
-    param:void
-    # set -o errexit
-    if {
-        x log :yanfa warn "<release-pub> update"
-        ___x_cmd_yanfa_release_update "${CONCURRENCY:-7}"
-    } && {
-        x log :yanfa warn "<release-pub> create tgz"
-        ___x_cmd_yanfa_release_tgz "$@"
-        x log :yanfa warn "<release-pub> create tgz exit: $?"
-    } && {
-        x log :yanfa warn "<release-pub> Add && Commit && Push"
-        git add . && git commit -m ... && ___x_cmd_yanfa_ws_push
-        x log :yanfa warn "<release-pub> Add && Commit && Push exit: $?"
-    }; then
-        x log :yanfa warn "<release-pub> OK"
-    else
-        x log :yanfa warn "<release-pub> Fail"
-        return 1
-    fi
-)
 
 
 # Section: tgz tar 7z
