...

diff --git a/lib/release b/lib/release
--- a/lib/release
+++ b/lib/release
@@ -156,11 +156,21 @@ ___x_cmd_yanfa_release_lsfile()(
     [ -d "$___X_CMD_YANFA_RELEASE_TMP" ] || return 1
 
     ___x_cmd_yanfa_release_lsmod "$@" | (
-        if ! cd "$___X_CMD_YANFA_RELEASE_TMP"; then
-            yanfa:info "___x_cmd_yanfa_release_lsfile: fail to cd - $___X_CMD_YANFA_RELEASE_TMP"
-        fi
+        # if ! cd "$___X_CMD_YANFA_RELEASE_TMP"; then
+        #     yanfa:info "___x_cmd_yanfa_release_lsfile: fail to cd - $___X_CMD_YANFA_RELEASE_TMP"
+        # fi
+
+        cd "$___X_CMD_YANFA_RELEASE_TMP" && \
         while read -r line; do
-            ( cd "$line" && ___x_cmd_yanfa_mod_lsfile | x arg1 printf "%s/%s\n" "$line" )
+            (
+                # if ! cd "$line"; then
+                #     yanfa:info "___x_cmd_yanfa_release_lsfile while-loop: fail to cd - $line"
+                #     exit 1
+                # else
+                #     ___x_cmd_yanfa_mod_lsfile | x arg1 printf "%s/%s\n" "$line"
+                # fi
+                cd "$line" && ___x_cmd_yanfa_mod_lsfile | x arg1 printf "%s/%s\n" "$line"
+            )
         done
     )
 
